name: Deploy to NPM on release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Find and Replace NPM name
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "d3-sankey"
          replace: "@vizlib/d3-sankey"
          include: "package.json"
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Replace NPM version
        run: |
          npm --no-git-tag-version version ${{ env.GITHUB_REF_SLUG }}
      - name: Clean install dependencies
        run: yarn install --frozen-lockfile

      - name: Run deploy script
        run: |
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
